import Head from 'next/head';
import { HiOutlineViewGridAdd } from 'react-icons/hi';
import Table from '@/components/table';
import Form from '@/components/form';

export default function Manage() {
  return (
    <section>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="py-5">
        <h1 className="text-xl md:text-5xl text-center font-bold py-10">Item Management</h1>
        <div className="container mx-auto flex justify-between py-5 border-b">
          <div className="left flex gap-3">
            <button className="flex bg-indigo-500 text-white rounded-md hover:bg-indigo-700 hover:border-indigo-500 px-4 py-3">
              Add Item{' '}
              <span className="pl-2">
                <HiOutlineViewGridAdd size={23}></HiOutlineViewGridAdd>
              </span>
            </button>
          </div>
        </div>
        <div className="container mx-auto">
          <Form></Form>
        </div>
        <div className="container mx-auto">
          <Table></Table>
        </div>
      </main>
    </section>
  );
}
